import { IColumn } from '../types/table.columns';

export const columns: IColumn[] = [
    {
        indexSort: 2,
        fieldName: 'partName',
        fieldCaption: 'Разбивка',
        type: 'string',
        align: 'left',
        width: 150,
    },
    {
        indexSort: 3,
        fieldName: 'contractorName',
        fieldCaption: 'Контрагент',
        type: 'string',
        align: 'left',
        width: 350,
    },
    {
        indexSort: 4,
        fieldName: 'contractorCodeRegional',
        fieldCaption: 'Код МО',
        type: 'string',
        align: 'right',
        width: 100,
    },
    {
        indexSort: 5,
        fieldName: 'billOfContractor',
        fieldCaption: 'Счета МО',
        type: 'currency',
        align: 'right',
        width: 150,
    },
    {
        indexSort: 7,
        fieldName: 'sumWithholdingByMek',
        fieldCaption: 'МЭК',
        type: 'currency',
        align: 'right',
        width: 130,
    },
    {
        indexSort: 8,
        fieldName: 'sumWithholdingByMee',
        fieldCaption: 'МЭЭ',
        type: 'currency',
        align: 'right',
        width: 130,
    },
    {
        indexSort: 9,
        fieldName: 'sumWithholdingByEkmp',
        fieldCaption: 'ЭКМП',
        type: 'currency',
        align: 'right',
        width: 130,
    },
    {
        indexSort: 10,
        fieldName: 'paidByPrepaymentSum',
        fieldCaption: 'Аванс',
        type: 'currency',
        align: 'right',
        width: 130,
    },
    {
        indexSort: 12,
        fieldName: 'debtByBalanceSum',
        fieldCaption: 'Задолженность',
        type: 'currency',
        highlight: true,
        align: 'right',
        width: 130,
    },
    {
        indexSort: 13,
        fieldName: 'paidFromContractors',
        fieldCaption: 'Поступления от МО',
        type: 'currency',
        align: 'right',
        width: 100,
    },
    {
        indexSort: 14,
        fieldName: 'reorganizationContractor',
        fieldCaption: 'Реорганизация',
        type: 'currency',
        align: 'right',
        width: 130,
    },
    {
        indexSort: 16,
        fieldName: 'sumPos',
        fieldCaption: 'Сумма',
        type: 'currency',
        highlight: true,
        align: 'right',
        width: 150,
    },
    {
        indexSort: 17,
        fieldName: 'notPaid',
        fieldCaption: 'Не оплачено',
        type: 'currency',
        align: 'right',
        width: 150,
    },
    // {
    //     indexSort: 99,
    //     fieldName: 'actionCell',
    //     fieldCaption: 'Действия',
    //     type: 'action',
    //     width: 150,
    //     sortable: false,
    // },
];
